# -*- coding: utf-8 -*-
"""
150 ta keng tarqalgan, tekshirilgan ingliz idiomalari banki, CEFR darajasi
bilan (A2/B1/B2/C1). Har bir element: (idioma, inglizcha qisqa ma'no izohi,
CEFR daraja). AI bu ro'yxatdan TASODIFIY birini tanlab, uning ustida to'liq
dars (tushuntirish, misollar, test) tuzadi.
"""
import random

IDIOMS = [
    ("Break the ice", "to do or say something to reduce tension in a social situation", "B1"),
    ("Hit the nail on the head", "to describe exactly what is causing a situation or problem", "B2"),
    ("Once in a blue moon", "very rarely", "B1"),
    ("Let the cat out of the bag", "to reveal a secret accidentally", "B1"),
    ("Under the weather", "feeling slightly ill", "B1"),
    ("Piece of cake", "something very easy to do", "A2"),
    ("Cost an arm and a leg", "to be very expensive", "B1"),
    ("Break a leg", "used to wish someone good luck, especially before a performance", "A2"),
    ("Bite the bullet", "to force yourself to do something unpleasant or difficult", "B2"),
    ("Call it a day", "to stop working on something for the rest of the day", "B1"),
    ("Speak of the devil", "said when a person who was just mentioned suddenly appears", "B1"),
    ("On the ball", "alert, competent, and quick to understand things", "B2"),
    ("The best of both worlds", "to benefit from two different opportunities at the same time", "B1"),
    ("Beat around the bush", "to avoid talking about something directly", "B2"),
    ("See eye to eye", "to agree with someone", "B1"),
    ("Get out of hand", "to become uncontrollable", "B1"),
    ("Cut corners", "to do something the cheapest or easiest way, often sacrificing quality", "B2"),
    ("Straight from the horse's mouth", "information received directly from the original, reliable source", "B2"),
    ("Miss the boat", "to miss an opportunity because you were too slow", "B1"),
    ("Kill two birds with one stone", "to accomplish two things with a single action", "B1"),
    ("On thin ice", "in a risky or dangerous situation", "B2"),
    ("A blessing in disguise", "something bad that eventually results in something good", "B1"),
    ("A dime a dozen", "very common, not special", "B2"),
    ("Add insult to injury", "to make a bad situation even worse", "B2"),
    ("Barking up the wrong tree", "pursuing a mistaken course of action", "B2"),
    ("Break the bank", "to cost too much money", "B1"),
    ("Burn the midnight oil", "to work late into the night", "B2"),
    ("By the skin of your teeth", "just barely, by a very narrow margin", "C1"),
    ("Cost a fortune", "to be very expensive", "A2"),
    ("Cut to the chase", "to get to the point without wasting time", "B2"),
    ("Play devil's advocate", "to argue the opposite side just for the sake of debate", "C1"),
    ("Don't count your chickens before they hatch", "don't assume success before it actually happens", "B2"),
    ("Every cloud has a silver lining", "something good can come from a bad situation", "B1"),
    ("Fit as a fiddle", "in very good health", "B2"),
    ("Get a taste of your own medicine", "to be treated the way you have treated others", "B2"),
    ("Give someone the benefit of the doubt", "to trust what someone says even without full proof", "B2"),
    ("Go back to the drawing board", "to start a plan again from the beginning", "B1"),
    ("Hit the sack", "to go to bed", "A2"),
    ("In hot water", "in trouble", "B1"),
    ("It's not rocket science", "it's not difficult to understand", "B1"),
    ("Jump on the bandwagon", "to join a popular activity or trend", "B2"),
    ("Keep your chin up", "to stay positive during a difficult time", "B1"),
    ("Kill the mood", "to ruin a good atmosphere", "B1"),
    ("The last straw", "the final problem in a series that causes a strong reaction", "B1"),
    ("Let sleeping dogs lie", "to avoid bringing up an issue that could cause trouble", "B2"),
    ("To make a long story short", "to summarize a story briefly", "A2"),
    ("On the fence", "undecided about something", "B1"),
    ("Out of the blue", "unexpectedly, without warning", "A2"),
    ("Pull someone's leg", "to joke with someone, to tease", "B1"),
    ("Put all your eggs in one basket", "to risk everything on a single plan", "B1"),
    ("Rain on someone's parade", "to spoil someone's plans or happiness", "B2"),
    ("Read between the lines", "to understand the hidden meaning of something", "B1"),
    ("Ring a bell", "to sound familiar", "A2"),
    ("Rule of thumb", "a general, practical guideline", "B1"),
    ("Sit on the fence", "to avoid making a decision", "B2"),
    ("Spill the beans", "to reveal secret information", "B1"),
    ("Steal someone's thunder", "to take credit for someone else's achievement", "B2"),
    ("Take it with a grain of salt", "to not take something too seriously", "B2"),
    ("The ball is in your court", "it's your decision or turn to act", "B1"),
    ("Throw in the towel", "to give up", "B1"),
    ("Time flies", "time passes very quickly", "A2"),
    ("To be in the same boat", "to be in the same difficult situation as someone else", "B1"),
    ("Under the table", "secretly, often illegally", "B2"),
    ("Wrap your head around something", "to understand something complicated", "B2"),
    ("You can't judge a book by its cover", "don't judge something or someone by appearance alone", "A2"),
    ("A penny for your thoughts", "used to ask what someone is thinking", "B1"),
    ("Actions speak louder than words", "what you do matters more than what you say", "B1"),
    ("Back to square one", "starting over from the beginning", "B1"),
    ("Someone's bark is worse than their bite", "someone seems more aggressive than they really are", "B2"),
    ("Bite off more than you can chew", "to take on more responsibility than you can handle", "B2"),
    ("Break even", "to neither make a profit nor a loss", "B2"),
    ("Burst someone's bubble", "to destroy someone's illusion or happiness", "B2"),
    ("Come rain or shine", "no matter what happens", "B1"),
    ("Cross that bridge when we come to it", "to deal with a problem only when/if it arises", "B2"),
    ("Cry over spilled milk", "to be upset about something that can no longer be changed", "B1"),
    ("Down to the wire", "until the very last possible moment", "C1"),
    ("Draw the line", "to set a limit on what is acceptable", "B1"),
    ("Drive someone up the wall", "to annoy someone greatly", "B1"),
    ("Easy does it", "used to tell someone to be careful and slow down", "A2"),
    ("The elephant in the room", "an obvious problem that no one wants to discuss", "B2"),
    ("Face the music", "to accept the consequences of your actions", "B1"),
    ("Fall through the cracks", "to be neglected or overlooked", "B2"),
    ("Feel under the weather", "to feel sick", "B1"),
    ("A fish out of water", "to feel awkward in unfamiliar surroundings", "B1"),
    ("Get cold feet", "to become nervous about doing something you had planned", "B1"),
    ("Get the ball rolling", "to start something", "B1"),
    ("Give the green light", "to give permission to proceed", "B1"),
    ("Go the extra mile", "to make additional effort beyond what is expected", "B1"),
    ("Hang in there", "to stay strong during a difficult time", "A2"),
    ("Have a change of heart", "to change your opinion or decision", "B1"),
    ("Hit the ground running", "to start something with great energy right away", "B2"),
    ("Hold your horses", "to wait, be patient", "B1"),
    ("In the heat of the moment", "overwhelmed by immediate strong emotion", "B2"),
    ("It takes two to tango", "both people involved share responsibility", "B1"),
    ("Jump the gun", "to act too soon, before the proper time", "B2"),
    ("Keep an eye on", "to watch or monitor closely", "A2"),
    ("Keep your fingers crossed", "to hope for good luck", "A2"),
    ("Lend a hand", "to help someone", "A2"),
    ("Let the chips fall where they may", "to accept the outcome, whatever it turns out to be", "C1"),
    ("A long shot", "something unlikely to happen or succeed", "B1"),
    ("Make ends meet", "to manage financially with limited money", "B1"),
    ("Method to the madness", "a reasonable purpose behind seemingly odd behavior", "C1"),
    ("Miss the point", "to fail to understand the main issue", "B1"),
    ("No pain, no gain", "success requires effort and sacrifice", "A2"),
    ("Off the top of my head", "without careful thought, from memory", "B1"),
    ("On the same page", "in agreement, sharing the same understanding", "B1"),
    ("Out of the woods", "past the difficult or dangerous part of a situation", "B1"),
    ("Pull yourself together", "to calm down and regain control of your emotions", "B1"),
    ("Push the envelope", "to go beyond normal limits", "C1"),
    ("Put your foot down", "to take a firm stance about something", "B1"),
    ("Rock the boat", "to disturb a stable situation", "B1"),
    ("Save for a rainy day", "to save money for a future time of need", "A2"),
    ("See the light at the end of the tunnel", "to see hope after a long difficult period", "B1"),
    ("A shot in the dark", "a guess with little chance of being right", "B1"),
    ("Sit tight", "to wait patiently without acting", "B1"),
    ("Smell a rat", "to suspect that something is wrong", "B2"),
    ("Stab someone in the back", "to betray someone's trust", "B1"),
    ("Straight from the shoulder", "honestly and directly", "B2"),
    ("Take the bull by the horns", "to deal with a difficult situation confidently and directly", "B1"),
    ("The tip of the iceberg", "only a small visible part of a much larger problem", "B1"),
    ("Through thick and thin", "during both good times and bad times", "B1"),
    ("Tie the knot", "to get married", "A2"),
    ("Turn a blind eye", "to deliberately ignore something", "B2"),
    ("Under one's belt", "achieved or experienced already", "B2"),
    ("Up in the air", "undecided or uncertain", "B1"),
    ("Water under the bridge", "past problems that are no longer important", "B1"),
    ("Weather the storm", "to survive a difficult situation", "B1"),
    ("When pigs fly", "something that will never happen", "A2"),
    ("Wrap up", "to finish or conclude something", "A2"),
    ("You reap what you sow", "your actions will have consequences, good or bad", "B1"),
    ("A drop in the ocean", "a very small amount compared to what is needed", "B1"),
    ("A leopard can't change its spots", "people don't fundamentally change their character", "B2"),
    ("Add fuel to the fire", "to make a bad situation even worse", "B1"),
    ("Against the clock", "racing to meet a deadline", "B1"),
    ("All ears", "listening attentively", "A2"),
    ("At the drop of a hat", "immediately, without hesitation", "B2"),
    ("Bend over backwards", "to try very hard to help someone", "B1"),
    ("Better late than never", "it's better to do something late than not at all", "A2"),
    ("Bring home the bacon", "to earn money to support the family", "B2"),
    ("By and large", "generally speaking, overall", "B2"),
    ("Caught red-handed", "caught in the act of doing something wrong", "B1"),
    ("Clear the air", "to resolve a disagreement or misunderstanding", "B1"),
    ("Cut someone some slack", "to be less critical of someone", "B1"),
    ("Dressed to the nines", "dressed very smartly or formally", "B2"),
    ("Get your act together", "to improve your behaviour and organise yourself", "B1"),
    ("Go cold turkey", "to stop a habit suddenly and completely", "B2"),
    ("Hit the books", "to study hard", "A2"),
    ("In the nick of time", "just in time, at the last possible moment", "B1"),
    ("Keep something under your hat", "to keep something secret", "B1"),
    ("A sixth sense", "an intuitive perception beyond the five senses", "A2"),
]


def get_random_idiom() -> tuple:
    """Bankdan tasodifiy (idioma, ma'no, CEFR daraja) uchligini qaytaradi."""
    return random.choice(IDIOMS)
