# -*- coding: utf-8 -*-
"""
150 ta keng tarqalgan, tekshirilgan ingliz phrasal verblari banki, CEFR
darajasi bilan (A2/B1/B2/C1). Har bir element: (phrasal verb, inglizcha
qisqa ma'no izohi, CEFR daraja). AI bu ro'yxatdan TASODIFIY birini tanlab,
uning ustida to'liq dars (tushuntirish, misollar, test) tuzadi.
"""
import random

PHRASAL_VERBS = [
    ("Give up", "to stop trying or to quit", "A2"),
    ("Look after", "to take care of someone or something", "A2"),
    ("Look for", "to search for something", "A2"),
    ("Look forward to", "to anticipate something with pleasure", "A2"),
    ("Turn on", "to start a device or machine", "A2"),
    ("Turn off", "to stop a device or machine", "A2"),
    ("Turn down", "to refuse an offer; or to lower the volume", "B1"),
    ("Turn up", "to arrive; or to increase the volume", "B1"),
    ("Put off", "to postpone something", "B1"),
    ("Put on", "to wear clothing; or to start a device", "A2"),
    ("Put up with", "to tolerate something unpleasant", "B2"),
    ("Take off", "to remove clothing; (plane) to leave the ground; to become successful", "B1"),
    ("Take on", "to accept a responsibility or challenge", "B2"),
    ("Take after", "to resemble a family member", "B1"),
    ("Take up", "to start a new hobby or activity", "B1"),
    ("Bring up", "to raise a topic; or to raise a child", "B1"),
    ("Break down", "to stop functioning; or to become emotionally upset", "B1"),
    ("Break up", "to end a romantic relationship", "A2"),
    ("Break out", "to escape; or (fire/disease) to start suddenly", "B1"),
    ("Call off", "to cancel something", "B1"),
    ("Call back", "to return a phone call", "A2"),
    ("Carry on", "to continue doing something", "A2"),
    ("Carry out", "to perform or execute a task", "B2"),
    ("Check in", "to register at a hotel or airport", "A2"),
    ("Check out", "to leave a hotel; or to look at/examine something", "A2"),
    ("Come across", "to find something by chance; or to give an impression", "B2"),
    ("Come up with", "to think of an idea or solution", "B2"),
    ("Cut down on", "to reduce the amount of something", "B1"),
    ("Deal with", "to handle or manage a situation", "A2"),
    ("Drop off", "to fall asleep; or to leave someone/something somewhere", "B1"),
    ("Fall apart", "to break into pieces; or (a relationship) to fail", "B2"),
    ("Figure out", "to understand or solve something", "B1"),
    ("Fill in", "to complete a form; or to substitute for someone", "A2"),
    ("Find out", "to discover information", "A2"),
    ("Get along with", "to have a good relationship with someone", "B1"),
    ("Get away with", "to avoid punishment for something wrong", "B2"),
    ("Get back", "to return", "A2"),
    ("Get by", "to manage with limited resources", "B2"),
    ("Get over", "to recover from an illness or disappointment", "B1"),
    ("Get rid of", "to eliminate or dispose of something", "B1"),
    ("Get through", "to complete something difficult; or to make contact by phone", "B2"),
    ("Give away", "to give something as a gift; or to reveal a secret", "B1"),
    ("Give back", "to return something", "A2"),
    ("Give in", "to surrender or agree reluctantly", "B1"),
    ("Go ahead", "to proceed with something", "A2"),
    ("Go off", "(bomb/alarm) to explode or ring; or (food) to become bad", "B1"),
    ("Go on", "to continue; or to happen", "A2"),
    ("Go over", "to review or check something", "B1"),
    ("Grow up", "to become an adult", "A2"),
    ("Hand in", "to submit something, like homework", "A2"),
    ("Hand out", "to distribute something", "B1"),
    ("Hang on", "to wait; or to hold tightly", "A2"),
    ("Hang out", "to spend time relaxing or socialising", "A2"),
    ("Hold on", "to wait", "A2"),
    ("Hold up", "to delay something", "B2"),
    ("Keep on", "to continue doing something", "B1"),
    ("Keep up with", "to stay at the same pace or level as others", "B2"),
    ("Knock out", "to render someone unconscious", "B2"),
    ("Leave out", "to omit or exclude something", "B1"),
    ("Let down", "to disappoint someone", "B1"),
    ("Look into", "to investigate something", "B2"),
    ("Look out", "to be careful", "A2"),
    ("Look up", "to search for information, e.g. in a dictionary", "A2"),
    ("Make up", "to invent a story; or to reconcile after an argument", "B1"),
    ("Make up for", "to compensate for something", "B2"),
    ("Move in", "to start living in a new place", "A2"),
    ("Move out", "to leave a place of residence", "A2"),
    ("Pass away", "to die (a polite way of saying it)", "B1"),
    ("Pass out", "to faint", "B2"),
    ("Pick up", "to lift something; to collect someone; or to learn casually", "A2"),
    ("Point out", "to indicate or mention something", "B1"),
    ("Put away", "to store something in its proper place", "A2"),
    ("Put back", "to return something to its original place", "A2"),
    ("Put down", "to place something down; to write down; or to criticise", "B1"),
    ("Run into", "to meet someone unexpectedly", "B1"),
    ("Run out of", "to have no more of something left", "A2"),
    ("Set off", "to start a journey; or to trigger something", "B1"),
    ("Set up", "to arrange or establish something", "B1"),
    ("Show off", "to display something proudly to impress others", "B1"),
    ("Show up", "to arrive", "A2"),
    ("Shut down", "to stop operating", "B1"),
    ("Sort out", "to resolve or organise something", "B1"),
    ("Speak up", "to talk louder or express your opinion", "A2"),
    ("Stand for", "to represent something; or to tolerate", "B2"),
    ("Stand out", "to be noticeable", "B1"),
    ("Stay up", "to not go to bed", "A2"),
    ("Stick to", "to continue with something without changing", "B1"),
    ("Switch off", "to turn off a device", "A2"),
    ("Switch on", "to turn on a device", "A2"),
    ("Take back", "to retract a statement; or to return something", "B1"),
    ("Take down", "to remove something; or to write notes", "B1"),
    ("Talk over", "to discuss something thoroughly", "B2"),
    ("Think over", "to consider something carefully", "B1"),
    ("Throw away", "to discard something", "A2"),
    ("Try on", "to test clothing to check the fit", "A2"),
    ("Try out", "to test something", "B1"),
    ("Turn into", "to become or transform into something", "B1"),
    ("Wake up", "to stop sleeping", "A2"),
    ("Wear out", "to become unusable through use; or to exhaust someone", "B2"),
    ("Work out", "to exercise; to solve a problem; or to result successfully", "B1"),
    ("Write down", "to note something in writing", "A2"),
    ("Back up", "to support someone; or to make a copy of data", "B1"),
    ("Blow up", "to explode; to inflate; or to become very angry", "B1"),
    ("Break in", "to enter a place forcibly; or to interrupt", "B1"),
    ("Bring about", "to cause something to happen", "C1"),
    ("Bring back", "to return something; or to restore a memory", "B1"),
    ("Build up", "to increase gradually", "B1"),
    ("Burn out", "to become exhausted from work or stress", "B2"),
    ("Catch up", "to reach the same level or point as others", "B1"),
    ("Clean up", "to tidy something", "A2"),
    ("Come back", "to return", "A2"),
    ("Come out", "to be published or released; or to become known", "B1"),
    ("Cool down", "to become calmer or colder", "A2"),
    ("Count on", "to rely on someone or something", "B1"),
    ("Cover up", "to hide or conceal something", "B2"),
    ("Cut off", "to disconnect something; or to interrupt someone", "B1"),
    ("Do without", "to manage without something", "B2"),
    ("Dress up", "to wear formal or special clothes", "A2"),
    ("Drop by", "to visit briefly and informally", "B1"),
    ("Drop out", "to stop attending school or an activity", "B1"),
    ("Eat out", "to have a meal at a restaurant", "A2"),
    ("End up", "to finally be in a particular situation", "B1"),
    ("Face up to", "to accept and deal with a difficult situation", "C1"),
    ("Fall behind", "to fail to keep up with something", "B2"),
    ("Fall for", "to be attracted to, or tricked by, someone/something", "B2"),
    ("Fall out", "to have an argument with someone; or (hair) to come out", "B2"),
    ("Fill out", "to complete a form", "A2"),
    ("Fit in", "to belong or be accepted in a group", "B1"),
    ("Follow up", "to take further action on something", "B2"),
    ("Get in", "to enter or arrive somewhere", "A2"),
    ("Get off", "to leave a vehicle; or to finish work", "A2"),
    ("Get on", "to board a vehicle; or to have a good relationship", "A2"),
    ("Get out", "to leave a place", "A2"),
    ("Get together", "to meet socially", "A2"),
    ("Give out", "to distribute something; or to stop functioning", "B1"),
    ("Go along with", "to agree to support a plan or idea", "B2"),
    ("Go back", "to return to a place", "A2"),
    ("Go through", "to experience something difficult; or to examine thoroughly", "B1"),
    ("Hang up", "to end a phone call", "A2"),
    ("Hold back", "to restrain something; or to hesitate", "B2"),
    ("Hold off", "to delay doing something", "B2"),
    ("Keep away from", "to stay distant from something or someone", "B1"),
    ("Keep off", "to stay away from something, e.g. the grass", "B1"),
    ("Lay off", "to dismiss an employee from a job", "B2"),
    ("Look down on", "to consider someone inferior", "B2"),
    ("Look up to", "to admire or respect someone", "B1"),
    ("Pay back", "to repay money; or to take revenge", "B1"),
    ("Pull over", "to stop a vehicle at the side of the road", "B1"),
    ("Sort through", "to examine and organise a group of things", "B2"),
    ("Wind up", "to end up in a particular situation; or to finish something", "C1"),
]


def get_random_phrasal_verb() -> tuple:
    """Bankdan tasodifiy (phrasal verb, ma'no, CEFR daraja) uchligini qaytaradi."""
    return random.choice(PHRASAL_VERBS)
